### ISSUE TITLE
USER STORY: user can submit and select (correct example)

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/first-agile-project#6]
As a **user** I can **select and submit an answer from the poll** so that **i can provide my opinion with regards to certain running topics or events**

# Acceptance Criteria:

- user has the option to select a value from the poll
- when finished user can submit the poll and confirmation given
- Font is (set size) and easy to read
- users answers are stored once submitted

# Tasks

- [ ] create a submit button which submits the poll 
- [ ] create a poll with a number of checkbox questions
- [ ] add in error handling to check user has answered the poll questions
