### ISSUE TITLE
USER STORY: user anonymous feedback (correct example with acceptance criteria)

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/first-agile-project#7]
As a **user** I can **choose to hide my identity in poll response** so that **i can provide anonymous feedback**

Acceptance Criteria:

- The option should be provided as a checkbox
- The checkbox should be “checked” by default
- The option should appear next to the submit button
- After submitting the default submission confirmation should be adjusted to include the user name.

# Tasks

- [ ] code in a checkbox with the to title anonymous 
- [ ] when the poll first loads checkbox is checked
- [ ] when poll is submitted pop up message appears confirming this
