### ISSUE TITLE
USER STORY: user add comments (correct example)

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/first-agile-project#8]
As a **-user-** I can **-add a comment before i submit my poll resposne-** so that **-i can provider additonal thoughts beyond the response options as a user-**

Acceptance Criteria:

- users are given the option to add comments
- if a user inputs comments and submits they are logged
- a users comments are correctly logged against the poll they submit

# Tasks

- [ ] code in a text arena making sure it is not wider than poll
- [ ] width of the text area is a large enough for user to write mulit lines
- [ ] font size is readable of size 14px
